# templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-s3-api
spec:
  selector:
    app: {{ .Release.Name }}-s3-api
  ports:
    - protocol: TCP
      port: {{ .Values.s3api.port }}
      targetPort: {{ .Values.s3api.port }}
  type: NodePort
